services:
  trackplay-frontend:
    container_name: trackplay-frontend
    build:
      context: ./trackplay-frontend
    env_file:
      - .env.frontend
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./trackplay-frontend/public:/app/public
      - ./trackplay-frontend/src:/app/src
    networks:
      - trackplay-public
    depends_on:
      - trackplay-backend

  trackplay-backend:
    container_name: trackplay-backend
    build:
      context: ./trackplay-backend
    env_file:
      - .env.backend
    volumes:
      - ./trackplay-backend/prisma:/app/prisma
      - ./trackplay-backend/src:/app/src
      - ./.files/jwt/public.key:/app/.files/jwt/public.key:ro
    networks:
      - trackplay-public
      - trackplay-backend-internal
    depends_on:
      - trackplay-database
      - trackplay-auth
      - trackplay-igdb

  trackplay-database:
    image: postgres:alpine
    container_name: trackplay-database
    env_file:
      - .env.database
    volumes:
      - trackplay-database:/var/lib/postgresql/data
    networks:
      - trackplay-backend-internal
    restart: always

  trackplay-igdb:
    container_name: trackplay-igdb
    build:
      context: ./trackplay-igdb
    env_file:
      - .env.igdb
    volumes:
      - ./trackplay-igdb/src:/app/src
    networks:
      - trackplay-public

  trackplay-auth:
    container_name: trackplay-auth
    build:
      context: ./trackplay-auth
    env_file:
      - .env.auth
    volumes:
      - ./trackplay-auth/src:/app/src
      - ./.files/jwt/private.key:/app/.files/jwt/private.key:ro
    networks:
      - trackplay-backend-internal
      - trackplay-auth-internal
    depends_on:
      - trackplay-redis

  trackplay-redis:
    image: redis:alpine
    container_name: trackplay-redis
    env_file:
      - .env.redis
    command: sh -c "redis-server --bind $$HOST --requirepass $$REDIS_PASSWORD --save '' --appendonly no"
    volumes:
      - trackplay-redis:/data
    networks:
      - trackplay-auth-internal
    restart: unless-stopped

  trackplay-reverse:
    image: caddy:alpine
    container_name: trackplay-reverse
    ports:
      - 80:80
      - 443:443
    volumes:
      - trackplay-reverse:/data
      - trackplay-reverse:/config
      - ./.files/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./.files/caddy/certs:/etc/caddy/certs
    networks:
      - trackplay-public
    restart: unless-stopped

networks:
  trackplay-public:
  trackplay-backend-internal:
    internal: true
  trackplay-auth-internal:
    internal: true

volumes:
  trackplay-database:
    driver: local
  trackplay-redis:
    driver: local
  trackplay-reverse:
    driver: local
