services:
  trackplay-database:
    image: postgres:alpine
    container_name: trackplay-database
    env_file:
      - .env.database
    volumes:
      - trackplay-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trackplay-backend-internal
    restart: always

  trackplay-redis:
    image: redis:alpine
    container_name: trackplay-redis
    ports:
      - "6379:6379"
    networks:
      - trackplay-redis-internal

networks:
  trackplay-backend-internal:
  trackplay-redis-internal:

volumes:
  trackplay-database:
