services:
  trackplay-frontend:
    container_name: trackplay-frontend
    build:
      context: ./trackplay-frontend
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./trackplay-frontend:/app
    networks:
      - trackplay-network

  trackplay-backend:
    container_name: trackplay-backend
    build:
      context: ./trackplay-backend
    env_file:
      - .env.backend
    volumes:
      - ./trackplay-backend:/app
    networks:
      - trackplay-network
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - trackplay-database

  trackplay-database:
    image: postgres:alpine
    container_name: trackplay-database
    env_file:
      - .env.database
    volumes:
      - trackplay-database:/var/lib/postgresql/data
    networks:
      - trackplay-network
    restart: always

  trackplay-reverse:
    image: caddy:alpine
    container_name: trackplay-reverse
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./.files/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./.files/caddy/certs:/etc/caddy/certs
    networks:
      - trackplay-network
    restart: unless-stopped

networks:
  trackplay-network:

volumes:
  trackplay-database:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
