services:
  trackplay-frontend:
    container_name: trackplay-frontend
    build:
      context: ./trackplay-frontend
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./trackplay-frontend/public:/app/public
      - ./trackplay-frontend/src:/app/src
    networks:
      - trackplay-network
    depends_on:
      - trackplay-backend

  trackplay-backend:
    container_name: trackplay-backend
    build:
      context: ./trackplay-backend
    env_file:
      - .env.backend
    volumes:
      - ./trackplay-backend/prisma:/app/prisma
      - ./trackplay-backend/src:/app/src
    networks:
      - trackplay-network
    depends_on:
      - trackplay-database
      - trackplay-auth
      - trackplay-igdb

  trackplay-igdb:
    container_name: trackplay-igdb
    build:
      context: ./trackplay-igdb
    env_file:
      - .env.igdb
    volumes:
      - ./trackplay-igdb/src:/app/src
    networks:
      - trackplay-network

  trackplay-auth:
    container_name: trackplay-auth
    build:
      context: ./trackplay-auth
    env_file:
      - .env.auth
    volumes:
      - ./trackplay-auth/src:/app/src
    networks:
      - trackplay-network

  trackplay-database:
    image: postgres:alpine
    container_name: trackplay-database
    env_file:
      - .env.database
    volumes:
      - trackplay-database:/var/lib/postgresql/data
    networks:
      - trackplay-network
    restart: always

  trackplay-reverse:
    image: caddy:alpine
    container_name: trackplay-reverse
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./.files/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./.files/caddy/certs:/etc/caddy/certs
    networks:
      - trackplay-network
    restart: unless-stopped

networks:
  trackplay-network:

volumes:
  trackplay-database:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
